name: "Test"

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  test:
    strategy:
      matrix:
        go-version: [ 1.18.x, 1.19.x ]
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - run: go version

      - name: Check formatting
        run: diff -u <(echo -n) <(gofmt -d .)
        working-directory: api

      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.43

      - name: Test
        run: go test -v ./...
